# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 The Foundry Visionmongers Ltd

# Runs pytest on the matrix of supported platforms any Python versions.
name: Test
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test-Resolver
    runs-on: ubuntu-latest
    container:
      image: aswf/ci-vfxall:2022
    steps:
      - uses: actions/checkout@v3

      - name: Build and install (Docker)
        # The container only has cmake 3.12, so we use older (pre 3.15)
        # style build invocation.
        run: >
          cmake -S . -B build &&
          cmake --build build &&
          cmake --install build

      - run: |
          python -m pip install -r tests/requirements.txt

      - name: Test
        run: >
          cd tests
          python -m pytest . -v
