# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 The Foundry Visionmongers Ltd

# Runs pytest on the matrix of supported platforms any Python versions.
name: Test
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
#
jobs:
  build-openassetio:
    name: Build OpenAssetIO
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/openassetio/openassetio-build
    steps:
      - name: Checkout OpenAssetIO
        uses: actions/checkout@v3
        with:
          repository: OpenAssetIO/OpenAssetIO
          path: openassetio-checkout

      - name: Build OpenAssetIO
        run: |
          cd openassetio-checkout
          mkdir build
          cmake -G Ninja -S . -B build
          cmake --build build
          cmake --install build

      - uses: actions/upload-artifact@v3
        with:
          name: OpenAssetIO Build
          path: openassetio-checkout/build
          retention-days: 1

  test:
    # Must be run in response to the Build OpenAssetIO job.
    name: Test-Resolver
    runs-on: ubuntu-latest
    needs: build-openassetio
    container:
      image: aswf/ci-vfxall:2022-clang13.1
    steps:
      - uses: actions/checkout@v3

      - name: Get OpenAssetIO
        uses: actions/download-artifact@v3
        with:
          name: OpenAssetIO Build
          path: ./openassetio-build

      - name: Build and install Resolver
        run: |
          cmake -S . -DCMAKE_PREFIX_PATH="./openassetio-build/dist" -B build
          cmake --build build
          cmake --install build

      - run: |
          python -m pip install -r tests/requirements.txt

      - name: Test
        run: |
          export PXR_PLUGINPATH_NAME=$GITHUB_WORKSPACE/build/dist/resources/plugInfo.json
          export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib:$GITHUB_WORKSPACE/openassetio-build/dist/lib64
          export OPENASSETIO_DEFAULT_CONFIG=$GITHUB_WORKSPACE/tests/resources/openassetio.conf
          export PYTHONPATH=/usr/local/lib/python/:$GITHUB_WORKSPACE/openassetio-build/dist/lib/python3.9/site-packages
          cd tests
          python -m pytest . -v
